import type {
  AppNotification,
  DelayAnalysis,
  LiveTrainStatus,
  NetworkStatus,
  OperationalEvent,
  Train,
} from '@/lib/types'

export const TRAINS: Train[] = [
  {
    number: '12951',
    name: 'Mumbai Rajdhani',
    type: 'Rajdhani Express',
    from: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '04:55 PM' },
    to: { code: 'MMCT', station: 'Mumbai Central', city: 'Mumbai', time: '08:35 AM' },
    duration: '15h 40m',
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A'],
    status: 'late',
    delayMinutes: 12,
    eta: '08:47 AM',
  },
  {
    number: '12009',
    name: 'Shatabdi Express',
    type: 'Shatabdi Express',
    from: { code: 'MMCT', station: 'Mumbai Central', city: 'Mumbai', time: '06:00 AM' },
    to: { code: 'ADI', station: 'Ahmedabad Jn', city: 'Ahmedabad', time: '01:10 PM' },
    duration: '07h 10m',
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    classes: ['CC', 'EC'],
    status: 'on-time',
    delayMinutes: 0,
    eta: '01:10 PM',
  },
  {
    number: '12953',
    name: 'August Kranti Rajdhani',
    type: 'Rajdhani Express',
    from: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '05:10 PM' },
    to: { code: 'MMCT', station: 'Mumbai Central', city: 'Mumbai', time: '10:55 AM' },
    duration: '17h 45m',
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A'],
    status: 'running',
    delayMinutes: 4,
    eta: '10:59 AM',
  },
  {
    number: '12925',
    name: 'Paschim Express',
    type: 'Superfast Express',
    from: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '05:40 PM' },
    to: { code: 'MMCT', station: 'Mumbai Central', city: 'Mumbai', time: '12:10 PM' },
    duration: '18h 30m',
    runsOn: ['Mon', 'Wed', 'Fri', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    status: 'late',
    delayMinutes: 34,
    eta: '12:44 PM',
  },
  {
    number: '12909',
    name: 'Nizamuddin Garib Rath',
    type: 'Garib Rath',
    from: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '03:55 PM' },
    to: { code: 'BDTS', station: 'Bandra Terminus', city: 'Mumbai', time: '11:15 AM' },
    duration: '19h 20m',
    runsOn: ['Tue', 'Thu', 'Sat'],
    classes: ['3A'],
    status: 'cancelled',
    delayMinutes: 0,
    eta: '—',
  },
  {
    number: '22209',
    name: 'Duronto Express',
    type: 'Duronto Express',
    from: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '10:55 PM' },
    to: { code: 'MMCT', station: 'Mumbai Central', city: 'Mumbai', time: '04:05 PM' },
    duration: '17h 10m',
    runsOn: ['Mon', 'Wed', 'Sat'],
    classes: ['1A', '2A', '3A'],
    status: 'on-time',
    delayMinutes: 0,
    eta: '04:05 PM',
  },
  {
    number: '12985',
    name: 'Jaipur Double Decker',
    type: 'Double Decker Express',
    from: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '05:35 PM' },
    to: { code: 'JP', station: 'Jaipur Jn', city: 'Jaipur', time: '10:05 PM' },
    duration: '04h 30m',
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['CC', 'EC'],
    status: 'on-time',
    delayMinutes: 0,
    eta: '10:05 PM',
  },
  {
    number: '12015',
    name: 'Ajmer Shatabdi',
    type: 'Shatabdi Express',
    from: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '06:10 AM' },
    to: { code: 'JP', station: 'Jaipur Jn', city: 'Jaipur', time: '10:40 AM' },
    duration: '04h 30m',
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['CC', 'EC'],
    status: 'running',
    delayMinutes: 8,
    eta: '10:48 AM',
  },
  {
    number: '20608',
    name: 'Chennai Vande Bharat',
    type: 'Vande Bharat Express',
    from: { code: 'SBC', station: 'KSR Bengaluru', city: 'Bengaluru', time: '02:50 PM' },
    to: { code: 'MAS', station: 'MGR Chennai Central', city: 'Chennai', time: '07:20 PM' },
    duration: '04h 30m',
    runsOn: ['Mon', 'Tue', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['CC', 'EC'],
    status: 'on-time',
    delayMinutes: 0,
    eta: '07:20 PM',
  },
  {
    number: '12028',
    name: 'Bengaluru Shatabdi',
    type: 'Shatabdi Express',
    from: { code: 'SBC', station: 'KSR Bengaluru', city: 'Bengaluru', time: '06:00 AM' },
    to: { code: 'MAS', station: 'MGR Chennai Central', city: 'Chennai', time: '11:00 AM' },
    duration: '05h 00m',
    runsOn: ['Mon', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['CC', 'EC'],
    status: 'running',
    delayMinutes: 10,
    eta: '11:10 AM',
  },
  {
    number: '12986',
    name: 'Delhi Sarai Rohilla Double Decker',
    type: 'Double Decker Express',
    from: { code: 'JP', station: 'Jaipur Jn', city: 'Jaipur', time: '06:00 AM' },
    to: { code: 'NDLS', station: 'New Delhi', city: 'New Delhi', time: '10:30 AM' },
    duration: '04h 30m',
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['CC', 'EC'],
    status: 'on-time',
    delayMinutes: 0,
    eta: '10:30 AM',
  },
  {
    number: '20607',
    name: 'Mysuru Vande Bharat',
    type: 'Vande Bharat Express',
    from: { code: 'MAS', station: 'MGR Chennai Central', city: 'Chennai', time: '05:50 AM' },
    to: { code: 'SBC', station: 'KSR Bengaluru', city: 'Bengaluru', time: '10:20 AM' },
    duration: '04h 30m',
    runsOn: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat', 'Sun'],
    classes: ['CC', 'EC'],
    status: 'on-time',
    delayMinutes: 0,
    eta: '10:20 AM',
  },
]

const RAJDHANI_STATIONS: LiveTrainStatus['stations'] = [
  {
    code: 'NDLS',
    name: 'New Delhi',
    city: 'New Delhi',
    arrival: '',
    departure: '04:55 PM',
    predictedArrival: null,
    predictedDeparture: '04:55 PM',
    day: 1,
    status: 'departed',
    platform: '16',
    distanceFromOrigin: 0,
    delayMinutes: 0,
  },
  {
    code: 'KOTA',
    name: 'Kota Jn',
    city: 'Kota',
    arrival: '09:07 PM',
    departure: '09:12 PM',
    predictedArrival: '09:12 PM',
    predictedDeparture: '09:17 PM',
    day: 1,
    status: 'passed',
    platform: '1',
    distanceFromOrigin: 465,
    delayMinutes: 5,
  },
  {
    code: 'RTM',
    name: 'Ratlam Jn',
    city: 'Ratlam',
    arrival: '11:55 PM',
    departure: '12:00 AM',
    predictedArrival: '12:03 AM',
    predictedDeparture: '12:08 AM',
    day: 1,
    status: 'passed',
    platform: '2',
    distanceFromOrigin: 727,
    delayMinutes: 8,
  },
  {
    code: 'BRC',
    name: 'Vadodara Jn',
    city: 'Vadodara',
    arrival: '04:20 AM',
    departure: '04:25 AM',
    predictedArrival: '04:32 AM',
    predictedDeparture: '04:37 AM',
    day: 2,
    status: 'current',
    platform: '3',
    distanceFromOrigin: 1173,
    delayMinutes: 12,
  },
  {
    code: 'ST',
    name: 'Surat',
    city: 'Surat',
    arrival: '06:05 AM',
    departure: '06:10 AM',
    predictedArrival: '06:17 AM',
    predictedDeparture: '06:22 AM',
    day: 2,
    status: 'upcoming',
    platform: '4',
    distanceFromOrigin: 1302,
    delayMinutes: 12,
  },
  {
    code: 'BVI',
    name: 'Borivali',
    city: 'Mumbai',
    arrival: '08:05 AM',
    departure: '08:07 AM',
    predictedArrival: '08:17 AM',
    predictedDeparture: '08:19 AM',
    day: 2,
    status: 'upcoming',
    platform: '6',
    distanceFromOrigin: 1350,
    delayMinutes: 12,
  },
  {
    code: 'MMCT',
    name: 'Mumbai Central',
    city: 'Mumbai',
    arrival: '08:35 AM',
    departure: '',
    predictedArrival: '08:47 AM',
    predictedDeparture: null,
    day: 2,
    status: 'destination',
    platform: '5',
    distanceFromOrigin: 1387,
    delayMinutes: 12,
  },
]

export const MOCK_DELAY_ANALYSIS_12951: DelayAnalysis = {
  trainNumber: '12951',
  currentDelayMinutes: 12,
  predictedDelayMinutes: 12,
  scheduledArrival: '08:35 AM',
  predictedArrival: '08:47 AM',
  lastUpdatedSeconds: 20,
  generatedAt: 'Updated just now',
  predictionBasis: [
    'Real-time GPS transponder telemetry at Vadodara Jn (BRC)',
    'Current recorded section delay (+12m)',
    'Historical corridor pattern along Western Railway line',
    'Active junction signaling & section congestion',
    'ML model dynamic slack recovery calculation',
  ],
  factors: [
    {
      id: 'f1',
      type: 'current',
      label: 'Current Section Delay',
      description: 'Recorded dwell and transit delay at Vadodara Jn (BRC)',
      impactMinutes: 12,
      available: true,
    },
    {
      id: 'f2',
      type: 'network',
      label: 'Network Congestion',
      description: 'Section capacity and junction clearance approaching Surat',
      impactMinutes: 8,
      available: true,
    },
    {
      id: 'f3',
      type: 'speed',
      label: 'Speed Restrictions',
      description: 'Scheduled engineering caution order between Surat and Valsad',
      impactMinutes: 5,
      available: true,
    },
    {
      id: 'f4',
      type: 'historical',
      label: 'Historical Pattern',
      description: 'Typical peak morning delay accumulation along BRC–MMCT line',
      impactMinutes: 4,
      available: true,
    },
    {
      id: 'f5',
      type: 'preceding-train',
      label: 'Preceding Train Margin',
      description: 'Spacing buffer behind preceding express traffic on main line',
      impactMinutes: 2,
      available: true,
    },
    {
      id: 'f6',
      type: 'weather',
      label: 'Weather & Visibility',
      description: 'Clear track visibility and normal atmospheric conditions',
      impactMinutes: 0,
      available: true,
    },
    {
      id: 'f7',
      type: 'ml',
      label: 'ML Dynamic Adjustment',
      description: 'Predicted headway recovery along Borivali–Mumbai Central corridor',
      impactMinutes: -3,
      available: true,
    },
  ],
}

export const MOCK_DELAY_ANALYSIS: Record<string, DelayAnalysis> = {
  '12951': MOCK_DELAY_ANALYSIS_12951,
}

export const MOCK_OPERATIONAL_EVENTS_12951: OperationalEvent[] = [
  {
    id: 'ev-1',
    trainNumber: '12951',
    type: 'congestion',
    severity: 'warning',
    title: 'Section Congestion',
    message:
      'Heavy freight crossing & traffic congestion in Vadodara–Surat block section',
    section: 'Vadodara (BRC) → Surat (ST)',
    occurredAt: '08:22 AM',
    active: true,
  },
  {
    id: 'ev-2',
    trainNumber: '12951',
    type: 'speed-restriction',
    severity: 'info',
    title: 'Temporary Speed Restriction',
    message:
      'Caution order 45 km/h enforced near Bharuch bridge maintenance zone',
    section: 'Bharuch (BH) section',
    occurredAt: '08:10 AM',
    active: true,
  },
  {
    id: 'ev-3',
    trainNumber: '12951',
    type: 'delay',
    severity: 'warning',
    title: 'Departure Delay at Vadodara',
    message:
      'Platform regulation delay (+12 min) awaiting clear signal clearance',
    station: 'Vadodara Jn',
    stationCode: 'BRC',
    occurredAt: '08:31 AM',
    active: true,
  },
  {
    id: 'ev-4',
    trainNumber: '12951',
    type: 'weather',
    severity: 'info',
    title: 'Weather & Track Visibility',
    message:
      'Clear daylight track visibility, normal overhead traction operating conditions',
    section: 'Western Railway Corridor',
    occurredAt: '07:45 AM',
    active: true,
  },
  {
    id: 'ev-5',
    trainNumber: '12951',
    type: 'operational',
    severity: 'info',
    title: 'Platform Inspection Completed',
    message:
      'Pre-departure brake and coupling check completed at Ratlam Junction',
    station: 'Ratlam Jn',
    stationCode: 'RTM',
    occurredAt: '03:55 AM',
    resolvedAt: '04:15 AM',
    active: false,
  },
]

export const MOCK_OPERATIONAL_EVENTS: Record<string, OperationalEvent[]> = {
  '12951': MOCK_OPERATIONAL_EVENTS_12951,
}

export const MOCK_NETWORK_STATUS_12951: NetworkStatus = {
  trainNumber: '12951',
  currentSection: 'Vadodara (BRC) → Surat (ST)',
  currentStation: 'Vadodara Jn',
  currentStationCode: 'BRC',
  congestionLevel: 'moderate',
  affectedTrainCount: 6,
  networkDelayMinutes: 8,
  precedingTrainImpactMinutes: 2,
  sectionDelayMinutes: 8,
  averageSectionSpeedKmph: 62,
  statusMessage:
    'Moderate traffic congestion is affecting movement through the current corridor.',
  generatedAt: 'Updated 20s ago',
  lastUpdatedSeconds: 20,
}

export const MOCK_NETWORK_STATUS: Record<string, NetworkStatus> = {
  '12951': MOCK_NETWORK_STATUS_12951,
}

export const LIVE_STATUS: Record<string, LiveTrainStatus> = {
  '12951': {
    trainNumber: '12951',
    status: 'late',
    delayMinutes: 12,
    eta: '08:47 AM',
    originalArrival: '08:35 AM',
    currentStation: 'Vadodara Jn',
    nextStation: 'Surat',
    distanceRemaining: 214,
    totalDistance: 1387,
    speedKmh: 82,
    platform: '3',
    lastUpdatedSeconds: 20,
    progress: 0.845,
    stations: RAJDHANI_STATIONS,
    delayAnalysis: MOCK_DELAY_ANALYSIS_12951,
    operationalEvents: MOCK_OPERATIONAL_EVENTS_12951,
    networkStatus: MOCK_NETWORK_STATUS_12951,
  },
}

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    type: 'delay',
    title: 'Train running late',
    message: '12951 Mumbai Rajdhani is now delayed by 12 minutes.',
    trainNumber: '12951',
    time: '2 min ago',
    read: false,
  },
  {
    id: 'n2',
    type: 'platform',
    title: 'Platform changed',
    message: 'Arrival platform at Surat changed from 2 → 4.',
    trainNumber: '12951',
    time: '18 min ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'arrival',
    title: 'Arriving soon',
    message: 'Your train arrives at Vadodara Jn in 10 minutes.',
    trainNumber: '12951',
    time: '32 min ago',
    read: true,
  },
  {
    id: 'n4',
    type: 'departure',
    title: 'Departed on schedule',
    message: '12009 Shatabdi Express departed from Mumbai Central.',
    trainNumber: '12009',
    time: '1 hr ago',
    read: true,
  },
  {
    id: 'n5',
    type: 'info',
    title: 'Journey reminder',
    message: 'Your saved train 22209 Duronto Express runs tomorrow.',
    trainNumber: '22209',
    time: 'Yesterday',
    read: true,
  },
]

export const POPULAR_ROUTES = [
  { from: 'New Delhi', to: 'Mumbai' },
  { from: 'Mumbai', to: 'Ahmedabad' },
  { from: 'New Delhi', to: 'Jaipur' },
  { from: 'Bengaluru', to: 'Chennai' },
]

export const STATION_SUGGESTIONS = [
  'New Delhi',
  'Mumbai Central',
  'Ahmedabad Jn',
  'Kota Jn',
  'Vadodara Jn',
  'Surat',
  'Jaipur Jn',
  'Bengaluru',
  'Chennai Central',
  'Bandra Terminus',
]
